application: dhs-devclub-website

# Version 0.0.0
version: v0-0-0
api_version: 1
runtime: python27
threadsafe: true


handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /roster/listmembers
  script: roster.app

- url: /roster/(.*)/(.*)
  static_files: roster/club-members/\1/\2
  upload: roster/club-members/.*

- url: /angular
  static_dir: angular

- url: /res
  static_dir: res

- url: /bower_components
  static_dir: bower_components

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
