application: dhs-devclub-website

# Version 0.0.0
version: v0-0-0
api_version: 1
runtime: python27
threadsafe: true


handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /about.html
  script: roster.app

- url: /roster/member/(.*)/(.*)
  static_files: club-members/\1/\2
  upload: club-members/.*

- url: /(.*)
  static_files: site/\1
  upload: site/.*

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
